import {
  Container,
  Heading,
  SimpleGrid,
  Stack,
  Text,
  Box,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { NavBar } from "../components/common/navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>k_xor_yama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Container maxW={"5xl"}>
          <Stack
            textAlign={"center"}
            align={"center"}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 20, md: 28 }}
          >
            <Heading
              fontWeight={600}
              fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
              lineHeight={"110%"}
            >
              Portfolio{" "}
              <Text as={"span"} color={"orange.400"}>
                skelton
              </Text>
            </Heading>
          </Stack>
          <SimpleGrid minChildWidth="240px" spacing="20px">
            <Box bg="tomato" height="180px">
              Blog Post Skelton
            </Box>
            <Box bg="tomato" height="180px">
              Blog Post Skelton
            </Box>
            <Box bg="tomato" height="180px">
              Blog Post Skelton
            </Box>
            <Box bg="tomato" height="180px">
              Blog Post Skelton
            </Box>
            <Box bg="tomato" height="180px">
              Blog Post Skelton
            </Box>
          </SimpleGrid>
        </Container>
      </NavBar>
    </>
  );
};

export default Home;
