import { Container, Text, Heading } from "@chakra-ui/react";
import type { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import { NavBar } from "../components/common/navbar";
import { getLastArticle } from "../utils/fs";
import { Article } from "../types/article";
import { MarkDownBuilder } from "../components/common/markdownBuilder";

const Home = ({ article }: { article: Article }) => {
  return (
    <>
      <Head>
        <title>{article.title} - Hut K</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Container maxW={"75%"} py={5} centerContent={true} pl={10}>
          <Heading size="xl" py={2} as="h1" id="#title">
            {article.title}
          </Heading>
          <Text as="em">{article.created_at.slice(0, 10)}</Text>
        </Container>
        <MarkDownBuilder markdown={article.content} />
      </NavBar>
    </>
  );
};
export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const article = await getLastArticle("content");
  return {
    props: {
      article,
    },
  };
};
