import {
  Container,
  Heading,
  SimpleGrid,
  Stack,
  Text,
  Box,
  SlideFade,
  ScaleFade,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { AwsBadge } from "../components/common/awsBadge";
import { NavBar } from "../components/common/navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hut K - Whoami</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <AwsBadge width={128} height={128} />
      </NavBar>
    </>
  );
};

export default Home;
