import { Container, SimpleGrid } from "@chakra-ui/react";
import type { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { NavBar } from "../../components/common/navbar";
import { BlogPostWithImage } from "../../components/articles/articleCard";
import { Article } from "../../types/article";
import { getAllArticles } from "../../utils/fs";
interface Props {
  articles: Article[];
}

const Home = ({ articles }: Props) => {
  return (
    <>
      <Head>
        <title>Hut K - Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Container maxW={"100%"} py={5} centerContent={true}>
          <Container
            maxW={"95%"}
            minH="50vh"
            pt={4}
            centerContent={true}
            bgColor="white"
          >
            <SimpleGrid minChildWidth="360px" spacing="1px" w="100%">
              {articles.map((a) => (
                <BlogPostWithImage
                  title={a.title}
                  content={a.content}
                  createdAt={a.created_at}
                  id={a.id}
                  key={a.id}
                />
              ))}
            </SimpleGrid>
          </Container>
        </Container>
      </NavBar>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const articles = await getAllArticles("content");
  return {
    props: { articles },
  };
};
