import {
  Container,
  Heading,
  Stack,
  Text,
  Box,
  Stat,
  StatLabel,
  StatNumber,
  StatHelpText,
  keyframes,
} from "@chakra-ui/react";
import type { GetStaticProps } from "next";
import Head from "next/head";
import { ReactNode, useState } from "react";
import { motion } from "framer-motion";
import { AwsBadge } from "../../components/common/awsBadge";
import { NavBar } from "../../components/common/navbar";
import { DownloadButton } from "../../components/downloadButton";
import { BarGraph } from "../../components/graph/bar";
import { BarandLineGraph } from "../../components/graph/barAndLine";
import { AtcoderRateIndicatior } from "../../components/whoami/atcoder/atcoderRateIndicatior";
import { AtcoderSolveDelta } from "../../components/whoami/atcoder/atcoderSolveDelta";
import {
  AtcoderAcResult,
  AtcoderContestResult,
  AtcoderInfo,
} from "../../types/atcoder";
import { WakatimeInfo } from "../../types/wakatime";
import { generateAtcoderGradientColor } from "../../utils/atcoderRateColor";
import { diffDates, getPastDate } from "../../utils/date";
import { getLatestAtcoderInfo, getLatestWakatimeInfo } from "../../utils/fs";
import {
  convertAtcoderAcDataToGraphData,
  convertAtcoderContestDataToGraphData,
  convertWakatimeActivitiesDataToGraphData,
  convertWakatimeLanguagesDataToGraphData,
} from "../../utils/graphData";
import { ATCODER_GRAPH_DATA_COUNT } from "../../const";
import { PolarGraph } from "../../components/graph/polar";
import { ScatterGraph } from "../../components/graph/scatter";

const graphID = [
  "hoursOfCoding",
  "Languages",
  "AtcoderPerformanceAndRate",
  "AtcoderACCount",
];
const animationKeyframes = keyframes`
  0% { transform: scale(1) rotate(0); }
  25% { transform: scale(1.05) rotate(0); }
  50% { transform: scale(1) rotate(0); }
`;
type Props = {
  latestContest: AtcoderContestResult;
  acCount: number;
  solveCount: AtcoderAcResult;
  previousCount: AtcoderAcResult;
  contestParticipationCount: number;
  children: ReactNode;
} & AtcoderInfo &
  WakatimeInfo;

const animationTwoSecound = `${animationKeyframes} 2s ease-in-out infinite`;
const animationThreeSecound = `${animationKeyframes} 3s ease-in-out infinite`;
const animationFiveSecound = `${animationKeyframes} 5s ease-in-out infinite`;
const Home = (props: Props) => {
  const hoursOfCoding = props.daily_avg.data.current_user.total.text;
  const dailyAvg = props.daily_avg.data.current_user.daily_average.text;
  const languageData = props.language.data.languages;
  const atcoderLatestContest = props.latestContest;
  const atcoderAcCount = props.acCount;
  const atcoderContestParticipationCount = props.contestParticipationCount;
  const today = new Date();
  const { day } = diffDates(new Date("2020-12-01"), today);
  const state = Object.fromEntries(
    graphID.map((x, i) => {
      if (i === 1 || i === 3) {
        return [x, true];
      } else {
        return [x, false];
      }
    })
  );
  const [graphState, setGraphState] = useState(state);
  const atcoderGraphInfo = convertAtcoderContestDataToGraphData(
    props.contestHistories,
    ATCODER_GRAPH_DATA_COUNT
  );
  const atcoderACInfo = convertAtcoderAcDataToGraphData(props.acCountHistories);
  const latestPerformanceColor = generateAtcoderGradientColor(
    atcoderLatestContest.Performance
  );

  return (
    <>
      <Head>
        <title>Hut K - Whoami</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Container maxW={"80%"} py={5} centerContent={true}>
          <Container
            maxW={"100%"}
            pt={4}
            centerContent={true}
            bgColor="gray.900"
          >
            <Heading size="xl" py={4}>
              Who am I ?
            </Heading>
            <DownloadButton
              colorScheme="purple"
              variant="outline"
              href="/resume_sojiro_koyama.docx"
              label="Resume"
            />

            <Stack direction="row" spacing={8} pt={4} pb={2} mx={2} w="75%">
              <Stat border="1px" borderColor="gray.200" p={2} borderRadius="lg">
                <StatLabel>Days since I became an Engineer</StatLabel>
                <StatNumber>{day} days</StatNumber>
                <StatHelpText>2020-12-01 ~ {getPastDate(0)}</StatHelpText>
              </Stat>
              <Stat
                as={motion.div}
                animation={animationTwoSecound}
                border="1px"
                borderColor="gray.200"
                bgColor="purple.900"
                p={2}
                borderRadius="lg"
                boxShadow={graphState[`${graphID[0]}`] ? "2xl" : ""}
                opacity={graphState[`${graphID[0]}`] ? "1.0" : "0.7"}
                id={graphID[0]}
                onMouseOver={(e) => {
                  const state = { ...graphState };
                  Object.keys(state).forEach((k) => {
                    if (k === graphID[1]) {
                      state[k] = false;
                    }
                  });
                  setGraphState({ ...state, [e.currentTarget.id]: true });
                }}
              >
                <StatLabel>This year&apos;s hours of coding</StatLabel>
                <StatNumber>{hoursOfCoding}</StatNumber>
                <StatHelpText>Daily Avg: {dailyAvg}</StatHelpText>
              </Stat>
              <Stat
                border="1px"
                borderColor="gray.200"
                p={2}
                as={motion.div}
                animation={animationThreeSecound}
                borderRadius="lg"
                bgColor="blue.900"
                id={graphID[1]}
                boxShadow={graphState[`${graphID[1]}`] ? "2xl" : ""}
                opacity={graphState[`${graphID[1]}`] ? "1.0" : "0.7"}
                onMouseOver={(e) => {
                  const state = { ...graphState };
                  Object.keys(state).forEach((k) => {
                    if (k === graphID[0]) {
                      state[k] = false;
                    }
                  });
                  setGraphState({ ...state, [e.currentTarget.id]: true });
                }}
              >
                <StatLabel>Most used language</StatLabel>
                <StatNumber>
                  <Box>{languageData[0].name}</Box>
                </StatNumber>
                <StatLabel>
                  Total Hours:{" "}
                  <Text as="em">
                    {(languageData[0].total_seconds / 3600)
                      .toString()
                      .substring(0, 6)}{" "}
                    Hs
                  </Text>
                </StatLabel>
              </Stat>
            </Stack>
            {graphState[`${graphID[1]}`] ? (
              <Box position="relative" h="25vw" w="29vw" my={8}>
                <PolarGraph
                  data={convertWakatimeLanguagesDataToGraphData(
                    props.language,
                    5
                  )}
                  title={`Top 5 ${graphID[1]}`}
                />
              </Box>
            ) : graphState[`${graphID[0]}`] ? (
              <Box position="relative" h="25vw" w="50vw" my={8}>
                <BarGraph
                  data={convertWakatimeActivitiesDataToGraphData(
                    props.activities,
                    7
                  )}
                  title="Last 7 days Activities"
                />
              </Box>
            ) : (
              <></>
            )}

            <Box position="relative" h="25vw" w="50vw" my={8}>
              {graphState[`${graphID[2]}`] ? (
                <BarandLineGraph
                  graphData={atcoderGraphInfo.graphData}
                  lineData={atcoderGraphInfo.lineData}
                  barData={atcoderGraphInfo.barData}
                  title="Atcoder Rate and Performance"
                />
              ) : graphState[`${graphID[3]}`] ? (
                <ScatterGraph data={atcoderACInfo.graphData} title="" />
              ) : (
                <></>
              )}
            </Box>
            <Stack direction="row" spacing={8} pt={4} pb={2} mx={2} w="75%">
              <Stat
                flex="2"
                border="1px"
                borderColor="gray.200"
                p={2}
                as={motion.div}
                animation={animationFiveSecound}
                borderRadius="lg"
                boxShadow={graphState[`${graphID[2]}`] ? "2xl" : ""}
                bgGradient={`linear(to-t, ${latestPerformanceColor.color} ,black ${latestPerformanceColor.ratio}%)`}
                id={graphID[2]}
                opacity={graphState[`${graphID[2]}`] ? "1.0" : "0.7"}
                onMouseOver={(e) => {
                  const state = { ...graphState };
                  Object.keys(state).forEach((k) => {
                    if (k === graphID[3]) {
                      state[k] = false;
                    }
                  });
                  setGraphState({ ...state, [e.currentTarget.id]: true });
                }}
              >
                <StatLabel>Latest Atcoder Contest</StatLabel>
                <StatNumber>
                  Performance: {atcoderLatestContest.Performance}
                </StatNumber>
                <StatHelpText>
                  {atcoderLatestContest.ContestScreenName.slice(0, 6)}
                </StatHelpText>
              </Stat>
              <Stat
                border="1px"
                borderColor="gray.200"
                animation={animationThreeSecound}
                as={motion.div}
                p={2}
                borderRadius="lg"
                boxShadow="md"
                id={graphID[3]}
                opacity={graphState[`${graphID[3]}`] ? "1.0" : "0.7"}
                onMouseOver={(e) => {
                  const state = { ...graphState };
                  Object.keys(state).forEach((k) => {
                    if (k === graphID[2]) {
                      state[k] = false;
                    }
                  });
                  setGraphState({ ...state, [e.currentTarget.id]: true });
                }}
              >
                <StatLabel>Atcoder AC counts</StatLabel>
                <StatNumber pr={4}>
                  {atcoderAcCount} ({props.solveCount.ac_rank}th){" "}
                </StatNumber>
                <StatHelpText>
                  <AtcoderSolveDelta
                    previous={props.previousCount}
                    latest={props.solveCount}
                  />
                </StatHelpText>
              </Stat>
            </Stack>
            <Stack direction="row" spacing={12} pt={4} pb={2} w="75%">
              <Box
                w="50%"
                boxShadow={graphState[`${graphID[2]}`] ? "2xl" : ""}
                id={graphID[2]}
                opacity={graphState[`${graphID[2]}`] ? "1.0" : "0.7"}
              >
                <AtcoderRateIndicatior
                  oldRating={atcoderLatestContest.OldRating}
                  newRating={atcoderLatestContest.NewRating}
                />
              </Box>
              <Stat
                border="1px"
                borderColor="gray.200"
                ml={2}
                p={2}
                borderRadius="lg"
              >
                <StatLabel>Number of Atcoder contest entries</StatLabel>
                <StatNumber>
                  <Text as="i">{atcoderContestParticipationCount} </Text>
                  times
                </StatNumber>
                <StatHelpText>
                  Last participation:{" "}
                  {atcoderLatestContest.EndTime.substring(0, 10)}
                </StatHelpText>
              </Stat>
            </Stack>
          </Container>
          <Container
            maxW={"100%"}
            py={2}
            centerContent={true}
            bgColor="gray.900"
          >
            <Heading size="xl" py={4}>
              Achivement
            </Heading>
            <AwsBadge width={200} height={200} />
          </Container>
        </Container>
      </NavBar>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const { language, daily_avg, activities } = await getLatestWakatimeInfo();
  const { contestHistories, acCountHistories } = await getLatestAtcoderInfo();
  const latestContest = contestHistories[contestHistories.length - 1];
  const acCount = acCountHistories[acCountHistories.length - 1].ac_count;
  const solveCount = acCountHistories[acCountHistories.length - 1];
  const previousCount =
    acCountHistories.length > 1
      ? acCountHistories[acCountHistories.length - 2]
      : acCountHistories[acCountHistories.length - 1];
  const contestParticipationCount = contestHistories.length;
  return {
    props: {
      language,
      daily_avg,
      activities,
      acCountHistories,
      contestHistories,
      latestContest,
      acCount,
      solveCount,
      previousCount,
      contestParticipationCount,
    },
  };
};
